"""
This is a dictionary of the default settings for speed-cam.py
If you don't want to use a config.py file these will create the required
variables with default values.  Change dictionary values if you want different
variable default values.
A message will be displayed if a variable is Not imported from config.py.
Note: plugins can override default and config.py values if plugins are
      enabled.  This happens after config.py variables are imported
"""
default_settings = {
    'calibrate':True,
    'cal_obj_px_L2R':90,
    'cal_obj_mm_L2R':4700.0,
    'cal_obj_px_R2L':95,
    'cal_obj_mm_R2L':4700.0,
    'overlayEnable':False,
    'overlayName':"picam240",
    'gui_window_on':False,
    'show_thresh_on':False,
    'show_crop_on':False,
    'verbose':True,
    'display_fps':False,
    'log_data_to_CSV':False,
    'loggingToFile':False,
    'logFilePath':'speed-cam.log',
    'SPEED_MPH':False,
    'track_counter':5,
    'MIN_AREA':100,
    'show_out_range':True,
    'x_diff_max':20,
    'x_diff_min':1,
    'x_buf_adjust':10,
    'track_timeout':0.5,
    'event_timeout':0.3,
    'max_speed_over':0,
    'CAM_LOCATION':'None',
    'WEBCAM_SRC': "",
    'WEBCAM_WIDTH':320,
    'WEBCAM_HEIGHT':240,
    'WEBCAM_HFLIP':False,
    'WEBCAM_VFLIP':False,
    'CAMERA_WIDTH':320,
    'CAMERA_HEIGHT':240,
    'CAMERA_FRAMERATE':20,
    'CAMERA_ROTATION':0,
    'CAMERA_VFLIP':True,
    'CAMERA_HFLIP':True,
    'image_path':"media/images",
    'image_prefix':"speed-",
    'image_format':".jpg",
    'image_jpeg_quality': 95,
    'image_jpeg_optimize': False,
    'image_show_motion_area':True,
    'image_filename_speed':False,
    'image_text_on':True,
    'image_text_bottom':True,
    'image_font_size':12,
    'image_font_thickness':2,
    'image_font_scale':0.5,
    'image_font_color': (255, 255, 255),
    'image_bigger':3.0,
    'image_max_files':0,
    'imageSubDirMaxFiles':1000,
    'imageSubDirMaxHours':0,
    'imageRecentMax':100,
    'imageRecentDir':"media/recent",
    'spaceTimerHrs':0,
    'spaceFreeMB':500,
    'spaceMediaDir':'media/images',
    'spaceFileExt ':'jpg',
    'SHOW_CIRCLE':False,
    'CIRCLE_SIZE':5,
    'LINE_THICKNESS':1,
    'WINDOW_BIGGER':1.0,
    'BLUR_SIZE':10,
    'THRESHOLD_SENSITIVITY':20,
    'DB_DIR':"data",
    'DB_NAME':"speed_cam.db",
    'DB_TABLE':"speed",
    'GRAPH_PATH':'media/graphs',
    'GRAPH_ADD_DATE_TO_FILENAME':False,
    'GRAPH_RUN_TIMER_HOURS':0.5,
    'GRAPH_RUN_LIST':[['hour', 2, 0],['hour', 7, 10],
                      ['hour', 14, 10],['day', 28, 0]],
    'web_server_port':8080,
    'web_server_root':"media",
    'web_page_title':"SPEED-CAMERA Media",
    'web_page_refresh_on':True,
    'web_page_refresh_sec':"900",
    'web_page_blank':False,
    'web_image_height':"768",
    'web_iframe_width_usage':"70%",
    'web_iframe_width':"100%",
    'web_iframe_height':"100%",
    'web_max_list_entries':0,
    'web_list_height':"768",
    'web_list_by_datetime':True,
    'web_list_sort_descending':True,
    'image_sign_on':False,
    'image_sign_show_camera':False,
    'image_sign_resize':(1280, 720),
    'image_sign_text_xy':(100, 675),
    'image_sign_font_scale':30.0,
    'image_sign_font_thickness':60,
    'image_sign_font_color':(255, 255, 255),
    'image_sign_timeout':5
    }
